#!/bin/sh

# The following terraform resources or modules are missing mappings in the resources file:
# google_firebase_project
# google_storage_bucket_iam_policy
# TODO(glasnt): manually add. 


# DON'T REMOVE FROM test script.
CYAN='\033[0;36m'
BCYAN='\033[1;36m'
NC='\033[0m' # No Color
DIVIDER=$(printf %"$(tput cols)"s | tr " " "*")
DIVIDER+="\n"

function get_project_id() {
    local __resultvar=$1
    VALUE=$(gcloud config get-value project | xargs)
    eval $__resultvar="'$VALUE'"
}

function get_project_number() {
    local __resultvar=$1
    local PRO=$2
    VALUE=$(gcloud projects list --filter="project_id=$PRO" --format="value(PROJECT_NUMBER)" | xargs)
    eval $__resultvar="'$VALUE'"
}

# DISPLAY HELPERS
function section_open() {
    section_description=$1
    printf "$DIVIDER"
    printf "${CYAN}$section_description${NC} \n"
    printf "$DIVIDER"
}

function section_close() {
    printf "$DIVIDER"
    printf "${CYAN}$section_description ${BCYAN}- done${NC}\n"
    printf "\n\n"
}

function evalTest() {
    local command=$1
    local expected=$2

    local ERR=""
    got=$(eval $command 2>errFile)
    ERR=$(<errFile)

    if [ ${#ERR} -gt 0 ]; then
        if [ "$expected" = "EXPECTERROR" ]; then
            printf "Expected Error thrown \n"
            return
        fi

        printf "Halting - error: '$ERR'  \n"
        exit 1
    fi

    if [ "$got" != "$expected" ]; then
        printf "Halting: '$got' expected '$expected'  \n"
        exit 1
    fi

    printf "$expected is ok\n"
}
# END DON'T REMOVE FROM test script.

get_project_id PROJECT
get_project_number PROJECT_NUMBER $PROJECT
PROJECT_ID=ds-tester-firebase-cloudrun
SERVICE_NAME=server
INSTANCE_NAME=psql
DATABASE_NAME=django
DATABASE_USERNAME=server

REGION=us-central1

terraformDIR=provisioning/terraform

gcloud config set project ${PROJECT}

terraform -chdir="$terraformDIR"  init
terraform -chdir="$terraformDIR"  apply  \
   -var project_id=$PROJECT_ID \
   -var service_name=$SERVICE_NAME \
   -var database_name=$DATABASE_NAME \
   -var instance_name=$INSTANCE_NAME \
   -auto-approve


section_open "Test google_cloud_run_service exists"
    evalTest 'gcloud run services describe $SERVICE_NAME --region $REGION --format="value(name)"' "$SERVICE_NAME"
section_close

section_open "Test google_cloud_run_v2_job setup exists"
    evalTest 'gcloud beta run jobs describe setup --region $REGION --format="value(name)"' "setup"
section_close

section_open "Test google_cloud_run_v2_job migrate exists"
    evalTest 'gcloud beta run jobs describe migrate --region $REGION --format="value(name)"' "migrate"
section_close

section_open "Test google_storage_bucket exists"
    evalTest 'gsutil ls | grep -c gs://media-$PROJECT' "1"
section_close

section_open "Test google_sql_database_instance exists"
    evalTest 'gcloud sql instances describe $INSTANCE_NAME --format="value(name)"' "$INSTANCE_NAME"
section_close

section_open "Test google_secret_manager_secret exists"
    evalTest 'gcloud secrets describe django_settings --format="value(name)"' "projects/$PROJECT_NUMBER/secrets/django_settings"
section_close

section_open "Test google_secret_manager_secret exists"
    evalTest 'gcloud secrets describe django_admin_password --format="value(name)"' "projects/$PROJECT_NUMBER/secrets/django_admin_password"
section_close

section_open "Test google_service_account exists"
    evalTest 'gcloud iam service-accounts describe api-backend@${PROJECT_ID}.iam.gserviceaccount.com --format="value(email)"' "api-backend@${PROJECT_ID}.iam.gserviceaccount.com"
section_close

section_open "Test google_service_account exists"
    evalTest 'gcloud iam service-accounts describe client-frontend@${PROJECT_ID}.iam.gserviceaccount.com --format="value(email)"' "client-frontend@${PROJECT_ID}.iam.gserviceaccount.com"
section_close

section_open "Test google_service_account exists"
    evalTest 'gcloud iam service-accounts describe automation@${PROJECT_ID}.iam.gserviceaccount.com --format="value(email)"' "automation@${PROJECT_ID}.iam.gserviceaccount.com"
section_close

section_open "Test google_project_iam_binding exists"
    evalTest 'gcloud projects get-iam-policy $PROJECT_ID --flatten="bindings[].members" --filter="bindings.role=roles/run.viewer" --format="value(bindings.members)"'  "serviceAccount:api-backend@${PROJECT_ID}.iam.gserviceaccount.com"
    evalTest 'gcloud projects get-iam-policy $PROJECT_ID --flatten="bindings[].members" --filter="bindings.role=roles/cloudsql.client bindings.members~api-backend" --format="value(bindings.members)"'  "serviceAccount:api-backend@${PROJECT_ID}.iam.gserviceaccount.com"
    evalTest 'gcloud projects get-iam-policy $PROJECT_ID --flatten="bindings[].members" --filter="bindings.role=roles/cloudsql.client bindings.members~automation" --format="value(bindings.members)"'  "serviceAccount:automation@${PROJECT_ID}.iam.gserviceaccount.com"
section_close

section_open "Prime database"
    gcloud beta run jobs execute setup --wait --region $REGION
section_close

section_open "UX tests"
    gcloud builds submit --config provisioning/automation/test.cloudbuild.yaml
section_close


terraform -chdir="$terraformDIR"  destroy  \
   -var project_id=$PROJECT_ID \
   -auto-approve


section_open "Test google_cloud_run_service does not exists"
    evalTest 'gcloud run services describe $SERVICE_NAME --region $REGION --format="value(name)"' "EXPECTERROR"
section_close

section_open "Test google_cloud_run_v2_job setup does not exists"
    evalTest 'gcloud run services describe setup --region $REGION --format="value(name)"' "EXPECTERROR"
section_close

section_open "Test google_cloud_run_v2_job migrate does not exists"
    evalTest 'gcloud run services describe migrate --region $REGION --format="value(name)"' "EXPECTERROR"
section_close

section_open "Test google_storage_bucket does not exists"
    evalTest 'gsutil ls | grep -c gs://media-$PROJECT' "0"
section_close

section_open "Test google_sql_database_instance does STILL exist (instance protection)"
    evalTest 'gcloud sql instances describe $INSTANCE_NAME --format="value(name)"' "$INSTANCE_NAME"
section_close

section_open "Test google_secret_manager_secret does not exists"
    evalTest 'gcloud secrets describe django_admin_password --format="value(name)"' "EXPECTERROR"
section_close

section_open "Test google_service_account does not exists"
    evalTest 'gcloud iam service-accounts describe api-backend@${PROJECT_ID}.iam.gserviceaccount.com --format="value(email)"' "EXPECTERROR"
section_close

section_open "Test google_service_account does not exists"
    evalTest 'gcloud iam service-accounts describe client-frontend@${PROJECT_ID}.iam.gserviceaccount.com --format="value(email)"' "EXPECTERROR"
section_close

section_open "Test google_service_account does not exists"
    evalTest 'gcloud iam service-accounts describe automation@${PROJECT_ID}.iam.gserviceaccount.com --format="value(email)"' "EXPECTERROR"
section_close

section_open "Test google_secret_manager_secret does not exists"
    evalTest 'gcloud secrets describe django_settings --format="value(name)"' "EXPECTERROR"
section_close

section_open "Test google_project_iam_binding does not exist"
    evalTest 'gcloud projects get-iam-policy $PROJECT_ID --flatten="bindings[].members" --filter="bindings.role=roles/run.viewer" --format="value(bindings.members)"'  ""
    evalTest 'gcloud projects get-iam-policy $PROJECT_ID --flatten="bindings[].members" --filter="bindings.role=roles/cloudsql.client" --filter="bindings.members~api-backend" --format="value(bindings.members)"'  ""
    evalTest 'gcloud projects get-iam-policy $PROJECT_ID --flatten="bindings[].members" --filter="bindings.role=roles/cloudsql.client" --filter="bindings.members~automation" --format="value(bindings.members)"'  ""
section_close

printf "$DIVIDER"
printf "CONGRATS!!!!!!! \n"
printf "You got the end the of your test with everything working. \n"
printf "$DIVIDER"