allowedCopyrightHolders:
  - "Google LLC"
  - "Google, Inc"

allowedLicenses:
  - "Apache-2.0"
  - "MIT"
  - "BSD-3"

ignoreFiles:
  - "**/package.json"
  - "**/package-lock.json"
  - "**/requirements.txt"
  - "**/requirements-test.txt"
  - "**/__init__.py"

ignoreLicenseYear: true

sourceFileExtensions:
  - "js"
  - "sh"
  - "Dockerfile"
  - "yml"
  - "py"
  - "html"
  - "txt"
