# .github/sync-repo-settings.yaml
# See https://github.com/googleapis/repo-automation-bots/tree/main/packages/sync-repo-settings for app options.
rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
deleteBranchOnMerge: true
branchProtectionRules:
- pattern: main
  isAdminEnforced: false
  requiresStrictStatusChecks: false
  requiredStatusCheckContexts:
    # .github/workflows/test.yml with a job called "test"
    - 'test'
    # .github/workflows/lint.yml with a job called "lint"
    - 'lint'
    # Google bots below
    - 'cla/google'
    - 'snippet-bot check'
    - 'header-check'
    - 'conventionalcommits.org'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
permissionRules:
  - team: workspace-devrel-dpe
    permission: admin
