# Generated by Django 4.1.3 on 2022-11-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="reviewer_location",
            field=models.CharField(max_length=100),
        ),
    ]
