# Generated by Django 5.1 on 2024-08-08 02:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="color_action",
            field=colorfield.fields.ColorField(
                default="#00AFAF",
                help_text="Fill for buttons",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_action_text",
            field=colorfield.fields.ColorField(
                default="#000000",
                help_text="Text for buttons",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_primary",
            field=colorfield.fields.ColorField(
                default="#C200C2",
                help_text="For the site banner gradient",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_secondary",
            field=colorfield.fields.ColorField(
                default="#BE0000",
                help_text="For headings",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="site_name_color",
            field=colorfield.fields.ColorField(
                default="#0D8645", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
