#!/usr/bin/python
#
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1 on 2024-08-08 02:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="color_action",
            field=colorfield.fields.ColorField(
                default="#00AFAF",
                help_text="Fill for buttons",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_action_text",
            field=colorfield.fields.ColorField(
                default="#000000",
                help_text="Text for buttons",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_primary",
            field=colorfield.fields.ColorField(
                default="#C200C2",
                help_text="For the site banner gradient",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_secondary",
            field=colorfield.fields.ColorField(
                default="#BE0000",
                help_text="For headings",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="site_name_color",
            field=colorfield.fields.ColorField(
                default="#0D8645", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
