steps:

  # Only run tests against the current project
  - id: "test"
    name: python:3.10-slim
    dir: provisioning
    script: |
        #!/bin/bash
        python -m pip install -r test/requirements.txt
        playwright install-deps  
        playwright install
        python -m pytest
