name: Terraform linting
on:
  push:
    branches: [ main ]
    paths:
      - 'provisioning/terraform/**/*.tf'
  pull_request:
    branches: [ main ]
    paths:
      - 'provisioning/terraform/**/*.tf'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: provisioning/terraform
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
      - name: Analysing the code with terraform
        timeout-minutes: 5
        run: |
          terraform fmt -check
