name: Terraform linting
on:
  push:
    branches: [ main ]
    paths:
      - 'provisioning/terraform/**/*.tf'
  pull_request:
    branches: [ main ]
    paths:
      - 'provisioning/terraform/**/*.tf'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: provisioning/terraform
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
        with:
          # Workaround for https://github.com/hashicorp/setup-terraform/issues/328
          terraform_wrapper: false
      - name: Analysing the code with terraform
        timeout-minutes: 5
        run: |
          terraform fmt -check -diff
