name: Server unit tests
on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: server
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Python Unit Tests
        timeout-minutes: 20
        run: |
          set -x
            echo "testing server"
            pushd
              python -m venv venv
              source venv/bin/activate
              cp .env.local .env
              pip install --upgrade pip
              pip install -r requirements.txt
              python -m pytest -v -p no:warnings
              bash scripts/prime_database.sh
              pytest
              deactivate
            popd
